---

- name: packages update list
  apt: >
    update_cache=yes
    cache_valid_time=60
  sudo: yes

- name: packages
  apt: >
    name={{ item }}
    state=latest
  with_items:
    - build-essential
    - wget
    - unzip
    - rsync
    - curl
    - acl
    - vim
  sudo: yes

- name: vim config syntax highlighting
  lineinfile: >
    dest=/etc/vim/vimrc
    line='syntax on'
    regexp='^"syntax on'
    state=present
    backrefs=yes
  sudo: yes
